config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {   registrations: 'users/registrations',
                                      sessions: 'users/sessions' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
resources :users, only: [:show]

get 'relaxes' => 'relaxes#cards'
get 'relaxes/cards' => 'relaxes#cards'
get 'tasks/tomato' => 'tasks#tomato'
root 'tasks#tomato'

  resources :tasks do
    resources :likes, only: [:create, :destroy]
  end

  resources :relaxes do
    resources :loves, only: [:create, :destroy]
    resources :comments, only: [:create]
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :relax
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :task
  belongs_to :user

  validates_uniqueness_of :task_id, scope: :user_id
end

app/models/lofe.rb
class Lofe < ApplicationRecord
  belongs_to :relax
  belongs_to :user

  validates_uniqueness_of :relax_id, scope: :user_id
end

app/models/love.rb
class Love < ApplicationRecord
  belongs_to :relax
  belongs_to :user

  validates_uniqueness_of :relax_id, scope: :user_id
end

app/models/relax.rb
class Relax < ApplicationRecord

    belongs_to :user

    mount_uploader :image, ImageUploader

    has_many :loves, dependent: :destroy
    has_many :loved_users, through: :loves, source: :user
    has_many :comments, dependent: :destroy
end

app/models/task.rb
class Task < ApplicationRecord

    belongs_to :user
    
    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


    validates :name, presence: true
    validates :profile, length: { maximum: 200 }

    has_many :tasks, dependent: :destroy
    has_many :likes, dependent: :destroy
    has_many :liked_tasks, through: :likes, source: :task

  def already_liked?(task)
    self.likes.exists?(task_id: task.id)
  end


  has_many :relaxes, dependent: :destroy
  has_many :loves, dependent: :destroy
  has_many :loved_relaxes, through: :loves, source: :relax
  has_many :comments, dependent: :destroy

  def already_loved?(relax)
    self.loves.exists?(relax_id: relax.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
    def configure_permitted_parameters
        # サインアップ時にnameのストロングパラメータを追加
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
        # アカウント編集の時にnameとprofileのストロングパラメータを追加
        devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile])
    end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
before_action :authenticate_user!

def create
    relax = Relax.find(params[:relax_id])
    comment = relax.comments.build(comment_params)
    comment.user_id = current_user.id
        if comment.save
            flash[:success] = "コメントしました"
            redirect_back(fallback_location: root_path)
        else
            flash[:success] = "コメントできませんでした"
            redirect_back(fallback_location: root_path)
        end
end

private

    def comment_params
    params.require(:comment).permit(:content)
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

    def create
        like = current_user.likes.create(task_id: params[:task_id])
        redirect_back(fallback_location: root_path)
    end

    def destroy
        like = Like.find_by(task_id: params[:task_id], user_id: current_user.id)
        like.destroy
        redirect_back(fallback_location: root_path)
    end

  end

app/controllers/loves_controller.rb
class LovesController < ApplicationController

    def create
        love = current_user.loves.create(relax_id: params[:relax_id])
        redirect_back(fallback_location: root_path)
    end
    
    def destroy
        love = Love.find_by(relax_id: params[:relax_id], user_id: current_user.id)
        love.destroy
        redirect_back(fallback_location: root_path)
    end

end

app/controllers/relaxes_controller.rb
class RelaxesController < ApplicationController

  def index
    if params[:search] == nil
      @relaxes= Relax.all.page(params[:page]).per(3).order(id: "DESC")
    elsif params[:search] == ''
      @relaxes= Relax.all.page(params[:page]).per(3).order(id: "DESC")
    else
      #部分検索
      @relaxes = Relax.where("body LIKE ? ",'%' + params[:search] + '%').page(params[:page]).per(3).order(id: "DESC")
      
    end
    @relax = Relax.new
  end

  def new
    @relax = Relax.new
  end

  def create
    relax = Relax.new(relax_params)
    relax.user_id = current_user.id
      if relax.save
      redirect_to :action => "index"
      else
      redirect_to :action => "new"
      end
  end

  def show
    @relax = Relax.find(params[:id])
    @comments = @relax.comments
    @comment = Comment.new
  end

  def edit
    @relax = Relax.find(params[:id])
  end

  def update
    relax = Relax.find(params[:id])
    if relax.update(relax_params)
      redirect_to :action => "show", :id => relax.id
    else
      redirect_to :action => "new"
    end
  end


  def destroy
    relax = Relax.find(params[:id])
    relax.destroy
    redirect_to action: :index
  end

  def cards
    if params[:search] == nil
      @relaxes= Relax.all.page(params[:page]).per(12).order(id: "DESC")
    elsif params[:search] == ''
      @relaxes= Relax.all.page(params[:page]).per(12).order(id: "DESC")
    else
      #部分検索
      @relaxes = Relax.where("body LIKE ? ",'%' + params[:search] + '%').page(params[:page]).per(12).order(id: "DESC")
      
  end

  
  @relax = Relax.new
    end

    private

    def relax_params
        params.require(:relax).permit(:title, :body, :image)
    end

    before_action :authenticate_user!, only: [:destroy, :edit, :update, :create, :new, :show]
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    if params[:search] == nil
      @tasks= Task.all.page(params[:page]).per(9).order(id: "DESC")
    elsif params[:search] == ''
      @tasks= Task.all.page(params[:page]).per(9).order(id: "DESC")
    else
      #部分検索
      @tasks = Task.where("body LIKE ? ",'%' + params[:search] + '%').page(params[:page]).per(9).order(id: "DESC")
    end
    @task = Task.new
  end

  def new
    @task = Task.new
  end

  def tomato
  end

  def create
    task = Task.new(task_params)
    task.user_id = current_user.id
      if task.save
      redirect_to :action => "index"
      else
      redirect_to :action => "new"
      end
  end

  def show
    @task = Task.find(params[:id])
  end

  def destroy
    task = Task.find(params[:id])
    task.destroy
    redirect_to action: :index
  end

  def tommy
    
  end

  private

  def task_params
    params.require(:task).permit(:title, :body)
  end

  before_action :authenticate_user!, only: [:destroy, :edit, :update, :create, :new]
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def show
        @user = User.find(params[:id])
    end
    

    before_action :authenticate_user!
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/loves_helper.rb
module LovesHelper
end

app/helpers/relaxes_helper.rb
module RelaxesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/relaxes/cards.html.erb
<%= stylesheet_link_tag 'cards', :media => "all" %>

<!DOCTYPE html>
<html lang="ja">

<div class="bg_pattern Paper_v2"></div>
<section id="second-block">
<br><br>
  <h1>投稿一覧</h1>
  <h2><%= link_to "新規息抜き投稿",new_relax_path %></h2>
  <br>
  <form>
    <label for="search">本文検索</label>
    <br>
    <input type="search" id="search" name="search">
  </form><br><br>

</section>


<section id="first-block">
<div class="row">
  <div class="col-1"></div>
  <div class="col-10">
    <div class="card-deck">
      <% @relaxes.each do |t| %>
        <div class="col-lg-4">
          <div class="card">
            <div class="card-header">
              
              <%= link_to relax_path(t.id) do %>
                <%= image_tag t.image_url, width: '100%', height: '100%' if t.image? %>
                <title><%= t.title %></title>
              
              <% end %>
            </div>
              <a class="btn btn-light" data-toggle="collapse" href="#collapseExample<%= t.id %>" role="button" aria-expanded="false" aria-controls="collapseExample">
                詳細表示
              </a>
            <div class="card-body">
              <div class="collapse" id="collapseExample<%= t.id %>">
                <ul class="list-group list-group-flush">
                  <li class="list-group-item1">
                      <h5 class="card-title"><b><%= t.title %></b></h5>
                      <p class="card-text"><%= t.body %></p>
                    </li>
                    <li class="list-group-item2"><a href="/users/<%= t.user.id %>">投稿者　　<%= t.user.name %></a>
                    </li>
                    <!-- <li class="list-group-item">Vestibulum at eros</li>
                -->
                </ul>
                <div class="card-footer">
                  <small class="text-muted">
                    <p class="time"><%= t.created_at.to_s(:datetime_jp) %></p>
                    <% if user_signed_in? %>
                      <% if current_user.already_loved?(t) %>
                        <%= link_to relax_lofe_path(id: t.id, relax_id: t.id), method: :delete do %>
                          <i class="fas fa-star fa-gold"></i><%= t.loves.count %>
                        <% end %>
                      <% else %>
                        <%= link_to relax_loves_path(id: t.id, relax_id: t.id), method: :post do %>
                          <i class="fas fa-star"></i><%= t.loves.count %>
                        <% end %>
                      <% end %>
                    <% else %>
                      <i class="fas fa-star"></i><%= t.loves.count %>
                    <% end %>
                    <a href="/relaxes/<%= t.id %>"><i class="fas fa-comments fa-blue"></i></a><%= t.comments.count %>
                    <%= link_to "もっと見る", relax_path(t.id) %>
                    <% if user_signed_in? && current_user.id == t.user_id %>
                      <%= link_to "削除", relax_path(t.id), method: :delete %>
                      <%= link_to "編集", edit_relax_path(t.id) %>
                    <% end %>
                  </small>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<%= paginate @relaxes %>

</section>



<section id="second-block">


  <form>
    <label for="search">本文検索</label>
    <br>
    <input type="search" id="search" name="search">
  </form><br><br>
<div class="wrap">

  <!-- Button trigger modal -->
  <button type="button" class="btn btn-info" data-toggle="modal" data-target="#exampleModalCenter">
  新規投稿
  </button>

    <!-- Modal -->
  <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header"><br>
          <h5 class="modal-title" id="exampleModalCenterTitle">新規投稿</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
          </button><br>
        </div>
        <div class="modal-body">
          <%= form_for(@relax, :url => { controller:'relaxes', action:'create'})do |f| %>
            <%= f.label :投稿内容 %>
            <%= f.text_area :title, :size => "10×1" %>
            <%= f.label :投稿詳細 %>
            <%= f.text_area :body,size: "50×10" %><br><br>
            <div class="field">
              <%= f.file_field :image %>
            </div><br>
          <button type="button" class="btn btn-secondary" data-dismiss="modal">閉じる</button>
          <button class="btn btn-info">投稿</button>
          <% end %>
        </div>
        <!-- <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">閉じる</button>
          <button type="button" class="btn btn-info">送信</button>
        </div> -->
      </div>
    </div>
  </div>
</div>
<br><br><br>



</section>


app/views/relaxes/edit.html.erb
<%= stylesheet_link_tag 'index', :media => "all" %>

<!DOCTYPE html>
<html lang="ja">


<br><br><br><br>
<section id="second-block">
        <p><%= image_tag @relax.image_url, size: "500x400" if @relax.image? %></p>


    <%= form_for @relax do |f| %>
        <%= f.label :title %>
            <%= f.text_field :title, :size => 140 %> 
        <%= f.label :body %>
            <%= f.text_field :body, :size => 140 %> 
        <%= f.submit "再投稿" %>
    <% end %>
</section>

app/views/relaxes/index.html.erb
<%= stylesheet_link_tag 'index', :media => "all" %>

<!DOCTYPE html>
<html lang="ja">




<br><br><br><br>

<section id="second-block">
<h1>投稿一覧</h1>
<h2><%= link_to "新規息抜き投稿",new_relax_path %></h2>
  <br>
  <form>
    <label for="search">本文検索</label>
    <br>
    <input type="search" id="search" name="search">
  </form><br><br>

<div class="relaxes-container">
  <div class="d-flex justify-content-center">
    <div class="box">
      <% @relaxes.each do |t| %>
        <div class="relax">
<!--
    <div class="card" style="width: 18rem;">
        <img src="..." class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title"><%= t.title %></h5>
            <p class="card-text"><%= t.body %></p>
            <a href="#" class="btn btn-primary">詳細へ</a>
        </div>
    </div>
-->
          <b><%= t.title %></b>
          <br>
          <%= image_tag t.image_url, size: "250x200" if t.image? %>
          <br>
          <div class="main-box">
            <div class="left-container">
              説明
              <br>
              <%= truncate(t.body, length:25) do%>
                (<%= link_to '続きを読む', relax_path(t.id) %>
              <% end %>
            </div>
            <div class="center-container">
              <br>
              <br>投稿者
              <br>
              <%= t.user.name %>
            </div>
            <div class="right-container">
              <% if user_signed_in? && current_user.id == t.user_id %>
                <%= link_to "削除", relax_path(t.id), method: :delete %>
                <%= link_to "編集", edit_relax_path(t.id) %>
              <% end %>
            </div>
          </div>
          <p class="time"><%= t.created_at.to_s(:datetime_jp) %></p>
          <% if user_signed_in? %>
            <% if current_user.already_loved?(t) %>
              <%= link_to relax_lofe_path(id: t.id, relax_id: t.id), method: :delete do %>
                <i class="fas fa-star fa-gold"></i><%= t.loves.count %>
              <% end %>
            <% else %>
              <%= link_to relax_loves_path(id: t.id, relax_id: t.id), method: :post do %>
                <i class="fas fa-star"></i><%= t.loves.count %>
              <% end %>
            <% end %>
          <% else %>
            <i class="fas fa-heart"></i><%= t.loves.count %>
          <% end %>

          <a href="/relaxes/<%= t.id %>"><i class="fas fa-comments fa-blue"></i></a><%= t.comments.count %>
          <%= link_to "詳細", relax_path(t.id) %>
        </div>
      <% end %>
    </div>
  </div>
</div>


<% @relaxes.each do |t| %>

<% end %>



<%= paginate @relaxes %>
</section>


<section id="third-block">
  <div id="wrapper">
    <div class="post-container">
    <p class="title">投稿フォーム</p>
      <%= form_for(@relax, :url => { controller:'relaxes', action:'create'})do |f| %>
      <%= f.label :投稿内容 %>
      <br>
      <%= f.text_area :title, :size => "10×1" %>
      <br>
      <%= f.label :投稿詳細 %>
      <br>
      <%= f.text_area :body,size: "50×10" %>
      <br>
        <div class="field">
          <%= f.label :image %>
          <br>
          <%= f.file_field :image %>
        </div>
        <br>
        <div class="wrap">
          <button class="button">送信</button>
        </div>
      <br><br><br><br>
      <% end %>
    </div>

</section>


app/views/relaxes/new.html.erb
<%= stylesheet_link_tag 'new', :media => "all" %>

<!DOCTYPE html>
<html lang="ja">

<br><br><br><br>
<div class="post-container">
    <p class="title">息抜き投稿フォーム</p>
    <%= form_for(@relax, :url => { controller:'relaxes', action:'create'})do |f| %>
        <%= f.label :投稿内容 %>
        <br>
        <%= f.text_area :title, :size => "10×1" %>
        <br>
        <%= f.label :投稿詳細 %>
        <br>
        <%= f.text_area :body,size: "50×10" %>
        <br>
            <div class="field">
                <%= f.label :image %>
                <br>
                <%= f.file_field :image %>
            </div>
            <br><br>
        <div class="wrap">
            <button class="button">送信</button>
        </div>
    <br>
    <% end %>
</div>

    <%= link_to "一覧に戻る", relaxes_cards_path %>

app/views/relaxes/show.html.erb
<%= stylesheet_link_tag 'show', :media => "all" %>

<!DOCTYPE html>
<html lang="ja">

<section id="second-block">
<br><br><br>
    <h3>息抜き詳細</h3>
    <div class="relax">
        <p><%= @relax.title %></p>
        <p><%= @relax.body %></p>
        <p><%= image_tag @relax.image_url, size: "500x400" if @relax.image? %></p>
        <p><%= @relax.created_at.to_s(:datetime_jp) %></p>

    <% if user_signed_in? %>
        <% if current_user.already_loved?(@relax) %>
            <%= link_to relax_lofe_path(@relax), method: :delete do %>
                <i class="fas fa-heart"></i><%= @relax.loves.count %>
            <% end %>
        <% else %>
            <%= link_to relax_loves_path(@relax), method: :post do %>
                <i class="fas fa-heart"></i><%= @relax.loves.count %>
            <% end %>
        <% end %>
    <% else %>
        <i class="fas fa-heart"></i><%= @relax.loves.count %>
    <% end %>

<div class="comment-wrapper">
    <p>コメント一覧</p>
    <% @comments.each do |c| %>
        <div>
        <%= c.user.name unless c.user.blank? %>
        <br>
        <%= c.content %>
        </div>
        <br>
    <% end %>

    <% if user_signed_in? %>
        <%= form_with(model: [@relax, @comment], local: true) do |f| %>
            <%= f.text_area :content %>
            <%= button_tag type: "submit" do %>
                <i class="far fa-comments"></i> コメントする
            <% end %>
        <% end %>
    <% end %>
</div>
    </div>
<h2>いいねしたユーザー</h2>
    <% @relax.loved_users.each do |user| %>
        <li><%= user.name %></li>
    <% end %>


    <%= link_to "編集する", edit_relax_path(@relax.id) %>
    <%= link_to "一覧に戻る", relaxes_cards_path %>


<br><br><br>
</section>

app/views/tasks/index.html.erb
<%= stylesheet_link_tag 'index', :media => "all" %>

<!DOCTYPE html>
<html lang="ja">

<div class="bg_pattern Paper_v2"></div>
<section id="second-block">
<br><br>
  <h1>投稿一覧</h1>
  <h2><%= link_to "新規タスク投稿",new_task_path %></h2>
  <br>

  <form>
    <label for="search">本文検索</label>
    <br>
    <input type="search" id="search" name="search">
  </form>

  <br><br>
<div class="row">
  <div class="col-1"></div>
  <div class="col-10">
    <div class="tasks-container">
      <% @tasks.each do |t| %>
        <div class="col-lg-4">
          <div class="task">
            <div style="background: #ccccbb; opacity: 0.2; transform: rotate(3deg); width: 35%; height: 35px; margin: 0 auto -1em auto;">
            </div><!-- ここまで付箋テープ -->
            
            <div class="l-border l-p-t l-p-r l-p-b l-p-l" style="background: #e2fde2; box-shadow: 4px 4px 4px rgba(0, 0, 0, 0.15); padding: 25px 15px 15px 15px;">
              <p style="margin: 0;">
              <b><h4><%= t.title %></b></h4>
                <div class="main-box"><br>
                  <div class="left-container">
                    <%= truncate(t.body, length:25) do%>
                      (<%= link_to '続きを読む', task_path(t.id) %>
                    <% end %>
                  </div>
                  <div class="center-container">
                    <a href="/users/<%= t.user.id %>"><%= t.user.name %></a>
                  </div>
                </div>
                  <p class="time"><%= t.created_at.to_s(:datetime_jp) %></p>
                <div class="right-container">
                  <%= link_to "詳細", task_path(t.id) %>
                  <% if user_signed_in? && current_user.id == t.user_id %>
                    <%= link_to "削除", task_path(t.id), method: :delete %>
                  <% end %>
                  <% if user_signed_in? %>
                    <% if current_user.already_liked?(t) %>
                      <%= link_to task_like_path(id: t.id, task_id: t.id), method: :delete do %>
                        <i class="fas fa-heartbeat fa-pink"></i><%= t.likes.count %>
                      <% end %>
                    <% else %>
                      <%= link_to task_likes_path(id: t.id, task_id: t.id), method: :post do %>
                        <i class="fas fa-heart"></i><%= t.likes.count %>
                      <% end %>
                    <% end %>
                  <% else %>
                    <i class="fas fa-heart"></i><%= t.likes.count %>
                  <% end %>
                </div>
              </p>
            </div><!-- ここまで付箋 -->
            <p>&nbsp;</p>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

  <%= paginate @tasks %>
  <br><br><br>
</section>


<section id="third-block">
  <div class="post-container">
    <p class="title">投稿フォーム</p>
    <%= form_for(@task, :url => { controller:'tasks', action:'create'})do |f| %>
      <%= f.label :投稿内容 %>
        <br>
      <%= f.text_area :title, :size => "10×1" %>
        <br>
      <%= f.label :投稿詳細 %>
        <br>
      <%= f.text_area :body,size: "50×10" %>
        <br>
        <br>
      <div class="wrap">
        <button class="button">送信</button>
      </div>
      <br>
    <% end %>
  </div>
</section>
    


app/views/tasks/new.html.erb
<%= stylesheet_link_tag 'new', :media => "all" %>

<!DOCTYPE html>
<html lang="ja">

<br><br><br><br>
<div class="post-container">
    <p class="title">新規タスク投稿フォーム</p>
    <%= form_for(@task, :url => { controller:'tasks', action:'create'})do |f| %>
    <%= f.label :タスク名を一言で！ %>
        <br>
        <%= f.text_area :title, :size => "10×1" %>
        <br>
        <%= f.label :タスク詳細 %>
        <br>
        <%= f.text_area :body,size: "50×10" %>
        <br>
            <div class="wrap">
                <button class="button">送信</button>
            </div>
    <br>
    <% end %>
</div>

    <%= link_to "一覧に戻る", tasks_path %>

app/views/tasks/show.html.erb
<%= stylesheet_link_tag 'show', :media => "all" %>

<!DOCTYPE html>
<html lang="ja">

<section id="second-block">
<br><br><br><br>
    <h3>タスク詳細</h3>
    <div class="task">
        <p><%= @task.title %></p>
        <p><%= @task.body %></p>
        <p><%= @task.created_at.to_s(:datetime_jp) %></p>
    

    <% if user_signed_in? %>
        <% if current_user.already_liked?(@task) %>
            <%= link_to task_like_path(@task), method: :delete do %>
            <i class="fas fa-heart"></i><%= @task.likes.count %>
            <% end %>
        <% else %>
            <%= link_to task_likes_path(@task), method: :post do %>
            <i class="fas fa-heart"></i><%= @task.likes.count %>
            <% end %>
        <% end %>
    <% else %>
        <i class="fas fa-heart"></i><%= @task.likes.count %>
    <% end %>
    </div>

<h2>いいねしたユーザー</h2>
    <% @task.liked_users.each do |user| %>
        <li><%= user.name %></li>
    <% end %>


<%= link_to "一覧に戻る", tasks_path %>

</section>

app/views/tasks/tomato.html.erb
<%= stylesheet_link_tag 'tomato', :media => "all" %>
  <div id="splash">
    <div id="splash_text" style="z-index:100"></div>
  </div>
      <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
<script src="https://rawgit.com/kimmobrunfeldt/progressbar.js/master/dist/progressbar.min.js"></script>

<!DOCTYPE html>
<html lang="ja">

<section id="first-block">

</section>

    