config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {   registrations: 'users/registrations',
                                      sessions: 'users/sessions' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
resources :users, only: [:show]

get 'relaxes' => 'relaxes#cards'
get 'relaxes/cards' => 'relaxes#cards'
get 'tasks/tomato' => 'tasks#tomato'
root 'tasks#tomato'

  resources :tasks do
    resources :likes, only: [:create, :destroy]
  end

  resources :relaxes do
    resources :loves, only: [:create, :destroy]
    resources :comments, only: [:create]
  end


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


    validates :name, presence: true
    validates :profile, length: { maximum: 200 }

    has_many :tasks, dependent: :destroy
    has_many :likes, dependent: :destroy
    has_many :liked_tasks, through: :likes, source: :task

  def already_liked?(task)
    self.likes.exists?(task_id: task.id)
  end


  has_many :relaxes, dependent: :destroy
  has_many :loves, dependent: :destroy
  has_many :loved_relaxes, through: :loves, source: :relax
  has_many :comments, dependent: :destroy

  def already_loved?(relax)
    self.loves.exists?(relax_id: relax.id)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def show
        @user = User.find(params[:id])
    end
    

    before_action :authenticate_user!
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<%= stylesheet_link_tag 'users', :media => "all" %>


<section id="second-block">
<div class="bg_pattern Paper_v2"></div>
  <div class=tasks_pro>
    <h1>user詳細</h1>
    <p>名前 : <%= @user.name %></p>
    <p>プロフィール : <%= @user.profile %></p>
  </div>
  <% if current_user.id == @user.id %>
    <%= link_to "編集する", edit_user_registration_path %>
  <% end %>

    <br><br><br><br>


  <h4>ユーザーの投稿一覧</h4><br>
  <h5>↓↓↓↓あなたのタスク投稿一覧↓↓↓↓</h5>
    <div class="tasks-container">
      <% @user.tasks.each do |t| %>
        <div class="col-lg-4">
          <div class="task">
            <div style="background: #ccccbb; opacity: 0.2; transform: rotate(3deg); width: 35%; height: 35px; margin: 0 auto -1em auto;">
            </div><!-- ここまで付箋テープ -->
            
            <div class="l-border l-p-t l-p-r l-p-b l-p-l" style="background: #ffffcc; box-shadow: 4px 4px 4px rgba(0, 0, 0, 0.15); padding: 25px 15px 15px 15px;">
              <p style="margin: 0;">
              <b><h4><%= t.title %></b></h4>
                <div class="main-box"><br>
                  <div class="left-container">
                    <%= truncate(t.body, length:25) do%>
                      (<%= link_to '続きを読む', task_path(t.id) %>
                    <% end %>
                  </div>
                </div>
                  <p class="time"><%= t.created_at.to_s(:datetime_jp) %></p>
                <div class="right-container">
                  <%= link_to "詳細", task_path(t.id) %>
                  <% if user_signed_in? && current_user.id == t.user_id %>
                    <%= link_to "削除", task_path(t.id), method: :delete %>
                  <% end %>
                  <% if user_signed_in? %>
                    <% if current_user.already_liked?(t) %>
                      <%= link_to task_like_path(id: t.id, task_id: t.id), method: :delete do %>
                        <i class="fas fa-heartbeat fa-pink"></i><%= t.likes.count %>
                      <% end %>
                    <% else %>
                      <%= link_to task_likes_path(id: t.id, task_id: t.id), method: :post do %>
                        <i class="fas fa-heart"></i><%= t.likes.count %>
                      <% end %>
                    <% end %>
                  <% else %>
                    <i class="fas fa-heart"></i><%= t.likes.count %>
                  <% end %>
                </div>
              </p>
            </div><!-- ここまで付箋 -->
            <p>&nbsp;</p>
          </div>
        </div>
      <% end %>
    </div>

    <br>
    <br>
    <br>
    <br>

  <h5>↓↓↓↓あなたの息抜き投稿一覧↓↓↓↓</h5><br>
  <div class="relaxes-container">
    <% @user.relaxes.each do |t| %>
    <div class="col-lg-4">
      <div class="relax">
        <b><%= t.title %></b>
        <br>
        <%= link_to relax_path(t.id) do %>
        <%= image_tag t.image_url ,size:"280x210" if t.image? %>
        <% end %>
        <br>
        <div class="main-box">

              <%= truncate(t.body, length:20) do%>
                  (<%= link_to '続きを読む', relax_path(t.id) %>
              <% end %>



              <% if user_signed_in? && current_user.id == t.user_id %>
                  <%= link_to "削除", relax_path(t.id), method: :delete %>
                  <%= link_to "編集", edit_relax_path(t.id) %>
              <% end %>

          <p class="time"><%= t.created_at.to_s(:datetime_jp) %></p>
        </div>
      </div>
    </div>
    <% end %>
    </div>
  </div>
</section>

<section id="third-block">
    <%= link_to "タスク一覧に戻る", tasks_path %>
    <%= link_to "息抜き一覧に戻る", relaxes_path %>
</section>


