config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {   registrations: 'users/registrations',
                                      sessions: 'users/sessions' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
resources :users, only: [:show]

get 'relaxes' => 'relaxes#cards'
get 'relaxes/cards' => 'relaxes#cards'
get 'tasks/tomato' => 'tasks#tomato'
root 'tasks#tomato'

  resources :tasks do
    resources :likes, only: [:create, :destroy]
  end

  resources :relaxes do
    resources :loves, only: [:create, :destroy]
    resources :comments, only: [:create]
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :relax
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :task
  belongs_to :user

  validates_uniqueness_of :task_id, scope: :user_id
end

app/models/lofe.rb
class Lofe < ApplicationRecord
  belongs_to :relax
  belongs_to :user

  validates_uniqueness_of :relax_id, scope: :user_id
end

app/models/love.rb
class Love < ApplicationRecord
  belongs_to :relax
  belongs_to :user

  validates_uniqueness_of :relax_id, scope: :user_id
end

app/models/relax.rb
class Relax < ApplicationRecord

    belongs_to :user

    mount_uploader :image, ImageUploader

    has_many :loves, dependent: :destroy
    has_many :loved_users, through: :loves, source: :user
    has_many :comments, dependent: :destroy
end

app/models/task.rb
class Task < ApplicationRecord

    belongs_to :user
    
    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


    validates :name, presence: true
    validates :profile, length: { maximum: 200 }

    has_many :tasks, dependent: :destroy
    has_many :likes, dependent: :destroy
    has_many :liked_tasks, through: :likes, source: :task

  def already_liked?(task)
    self.likes.exists?(task_id: task.id)
  end


  has_many :relaxes, dependent: :destroy
  has_many :loves, dependent: :destroy
  has_many :loved_relaxes, through: :loves, source: :relax
  has_many :comments, dependent: :destroy

  def already_loved?(relax)
    self.loves.exists?(relax_id: relax.id)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

    def create
        like = current_user.likes.create(task_id: params[:task_id])
        redirect_back(fallback_location: root_path)
    end

    def destroy
        like = Like.find_by(task_id: params[:task_id], user_id: current_user.id)
        like.destroy
        redirect_back(fallback_location: root_path)
    end

  end

app/controllers/loves_controller.rb
class LovesController < ApplicationController

    def create
        love = current_user.loves.create(relax_id: params[:relax_id])
        redirect_back(fallback_location: root_path)
    end
    
    def destroy
        love = Love.find_by(relax_id: params[:relax_id], user_id: current_user.id)
        love.destroy
        redirect_back(fallback_location: root_path)
    end

end

app/controllers/relaxes_controller.rb
class RelaxesController < ApplicationController

  def index
    if params[:search] == nil
      @relaxes= Relax.all.page(params[:page]).per(3).order(id: "DESC")
    elsif params[:search] == ''
      @relaxes= Relax.all.page(params[:page]).per(3).order(id: "DESC")
    else
      #部分検索
      @relaxes = Relax.where("body LIKE ? ",'%' + params[:search] + '%').page(params[:page]).per(3).order(id: "DESC")
      
    end
    @relax = Relax.new
  end

  def new
    @relax = Relax.new
  end

  def create
    relax = Relax.new(relax_params)
    relax.user_id = current_user.id
      if relax.save
      redirect_to :action => "index"
      else
      redirect_to :action => "new"
      end
  end

  def show
    @relax = Relax.find(params[:id])
    @comments = @relax.comments
    @comment = Comment.new
  end

  def edit
    @relax = Relax.find(params[:id])
  end

  def update
    relax = Relax.find(params[:id])
    if relax.update(relax_params)
      redirect_to :action => "show", :id => relax.id
    else
      redirect_to :action => "new"
    end
  end


  def destroy
    relax = Relax.find(params[:id])
    relax.destroy
    redirect_to action: :index
  end

  def cards
    if params[:search] == nil
      @relaxes= Relax.all.page(params[:page]).per(12).order(id: "DESC")
    elsif params[:search] == ''
      @relaxes= Relax.all.page(params[:page]).per(12).order(id: "DESC")
    else
      #部分検索
      @relaxes = Relax.where("body LIKE ? ",'%' + params[:search] + '%').page(params[:page]).per(12).order(id: "DESC")
      
  end

  
  @relax = Relax.new
    end

    private

    def relax_params
        params.require(:relax).permit(:title, :body, :image)
    end

    before_action :authenticate_user!, only: [:destroy, :edit, :update, :create, :new, :show]
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    if params[:search] == nil
      @tasks= Task.all.page(params[:page]).per(9).order(id: "DESC")
    elsif params[:search] == ''
      @tasks= Task.all.page(params[:page]).per(9).order(id: "DESC")
    else
      #部分検索
      @tasks = Task.where("body LIKE ? ",'%' + params[:search] + '%').page(params[:page]).per(9).order(id: "DESC")
    end
    @task = Task.new
  end

  def new
    @task = Task.new
  end

  def tomato
  end

  def create
    task = Task.new(task_params)
    task.user_id = current_user.id
      if task.save
      redirect_to :action => "index"
      else
      redirect_to :action => "new"
      end
  end

  def show
    @task = Task.find(params[:id])
  end

  def destroy
    task = Task.find(params[:id])
    task.destroy
    redirect_to action: :index
  end

  def tommy
    
  end

  private

  def task_params
    params.require(:task).permit(:title, :body)
  end

  before_action :authenticate_user!, only: [:destroy, :edit, :update, :create, :new]
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def show
        @user = User.find(params[:id])
    end
    

    before_action :authenticate_user!
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/loves_helper.rb
module LovesHelper
end

app/helpers/relaxes_helper.rb
module RelaxesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>


<html>

  <head>
    <title>とまとのプロダクト</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.14.0/css/all.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="http://coco-factory.jp/ugokuweb/wp-content/themes/ugokuweb/data/move02/5-11/css/reset.css">
    <link rel="stylesheet" type="text/css" href="http://coco-factory.jp/ugokuweb/wp-content/themes/ugokuweb/data/move02/5-11/css/5-11.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Bad+Script&family=Hachi+Maru+Pop&display=swap" rel="stylesheet">  
</head>

<link href="https://coco-factory.jp/ugokuweb/wp-content/themes/ugokuweb/data/reset.css" rel="stylesheet">
  <link href="https://coco-factory.jp/ugokuweb/wp-content/themes/ugokuweb/data/4-1-2/css/4-1-2.css" rel="stylesheet">
<body>


<!--script src="index.js"></script-->

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.js"></script>
  <main>
    <header>
      <div class="header-list" style="z-index:10" >
      <h1><%= link_to "TODAY'S TASK", tasks_tomato_path %></h1>
        <ul>
          <% if user_signed_in? %>
          <p><li><b><%= link_to "マイページ", user_path(current_user.id) %></b></li>
          <% end %>
          <li><b><%= link_to "タスク",tasks_path %></b></li>
          <li><b><%= link_to "息抜き",relaxes_cards_path %></b></li>
            <% if user_signed_in? %>
              <li><b><%=  link_to'ログアウト', destroy_user_session_path, method: :delete %></b></li>
              
            <% else %>
              <li><b><%= link_to "ログイン", new_task_path %></b></li>
              <li><b><%= link_to "新規登録", new_user_registration_path %></b></li>
            <% end %>
            </p>
        </ul>
      </div>
      
    </header>
    <p id="page-top"><a href="#">Page Top</a></p>
    <%= yield %>
      
      
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
            <!--JQuery読み込み-->
      <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
      <script src="https://rawgit.com/kimmobrunfeldt/progressbar.js/master/dist/progressbar.min.js"></script>

      <!--自作のJS-->
      <script src="https://coco-factory.jp/ugokuweb/wp-content/themes/ugokuweb/data/4-1-2/js/4-1-2.js"></script>
      <script>
      function PageTopAnime() {
	var scroll = $(window).scrollTop();
	if (scroll >= 200){//上から200pxスクロールしたら
		$('#page-top').removeClass('DownMove');//#page-topについているDownMoveというクラス名を除く
		$('#page-top').addClass('UpMove');//#page-topについているUpMoveというクラス名を付与
	}else{
		if($('#page-top').hasClass('UpMove')){//すでに#page-topにUpMoveというクラス名がついていたら
			$('#page-top').removeClass('UpMove');//UpMoveというクラス名を除き
			$('#page-top').addClass('DownMove');//DownMoveというクラス名を#page-topに付与
		}
	}
}

// 画面をスクロールをしたら動かしたい場合の記述
$(window).scroll(function () {
	PageTopAnime();/* スクロールした際の動きの関数を呼ぶ*/
});

// ページが読み込まれたらすぐに動かしたい場合の記述
$(window).on('load', function () {
	PageTopAnime();/* スクロールした際の動きの関数を呼ぶ*/
});

// #page-topをクリックした際の設定
$('#page-top a').click(function () {
    $('body,html').animate({
        scrollTop: 0//ページトップまでスクロール
    }, 500);//ページトップスクロールの速さ。数字が大きいほど遅くなる
    return false;//リンク自体の無効化
});
</script>

    </main>
    
    <footer>
      <p>Copyright © とまとん All Rights Reserved.</p>
    </footer>
  
</body>

</html>